### ISSUE TITLE
Warnings when installing hapi-pulse

### ISSUE THREAD

**Issue by tdukai** [futurestudio/hapi-pulse#146]
Hi I am getting the following yarn warnings: 

warning hapi-pulse > @hapi/joi@17.0.2: Switch to 'npm install joi'
warning hapi-pulse > @hapi/joi > @hapi/address@4.1.0: Moved to 'npm install @sideway/address'
warning hapi-pulse > @hapi/joi > @hapi/pinpoint@2.0.0: Moved to 'npm install @sideway/pinpoint'
warning hapi-pulse > @hapi/joi > @hapi/formula@2.0.0: Moved to 'npm install @sideway/formula'

I installed hapi-pulse 3.0.0
I am using @hapi/hapi: 20.1.3 and joi: 17.4.0

**Comment by marcuspoehls** [comment]
@tdukai Hey Tamara, thank you for your patience! Do you want to submit a pull request updating the dependencies?
